# Generated by Django 5.1.4 on 2024-12-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "project",
            "0010_remove_signup_email_item_bulk_price_item_chef_price_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="sale_id",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
