# Generated by Django 5.1.4 on 2024-12-25 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0012_sale_created_at_sale_customer_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sale",
            name="customer_name",
        ),
    ]
