# Generated by Django 5.1.4 on 2024-12-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0015_alter_item_i_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="i_type",
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
