# Generated by Django 5.1.4 on 2024-12-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0016_alter_item_i_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sale",
            old_name="cost",
            new_name="price",
        ),
        migrations.RemoveField(
            model_name="item",
            name="manufacturer",
        ),
        migrations.RemoveField(
            model_name="item",
            name="price",
        ),
        migrations.RemoveField(
            model_name="item",
            name="v_type",
        ),
        migrations.RemoveField(
            model_name="sale",
            name="manufacturer",
        ),
        migrations.RemoveField(
            model_name="sale",
            name="v_type",
        ),
        migrations.AddField(
            model_name="sale",
            name="subtotal",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
