# Generated by Django 5.1.4 on 2024-12-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0017_rename_cost_sale_price_remove_item_manufacturer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="payment_status",
            field=models.CharField(
                choices=[("Done", "Done"), ("Not Done", "Not Done")],
                default="Not Done",
                max_length=10,
            ),
        ),
    ]
