# Generated by Django 5.1.4 on 2024-12-25 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0018_sale_payment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="customer_name",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name="sale",
            name="payment_status",
            field=models.CharField(
                choices=[("paid", "paid"), ("paid", "unpaid")],
                default="unpaid",
                max_length=10,
            ),
        ),
    ]
