# Generated by Django 5.1.4 on 2024-12-26 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0019_sale_customer_name_alter_sale_payment_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sale",
            name="customer_name",
        ),
        migrations.AddField(
            model_name="item",
            name="gst",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sale",
            name="gst_subtotal",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
