# Generated by Django 5.1.4 on 2024-12-26 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0020_remove_sale_customer_name_item_gst_sale_gst_subtotal"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="customer_addrs",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="sale",
            name="customer_name",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
