# Generated by Django 5.1.4 on 2024-12-26 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0021_sale_customer_addrs_sale_customer_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="customer_mobile",
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
