# Generated by Django 5.1.4 on 2024-12-26 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0022_sale_customer_mobile"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="tsales",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
