# Generated by Django 5.1.4 on 2024-12-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0023_item_tsales"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="discount",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
