# Generated by Django 5.1.4 on 2024-12-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0024_sale_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="sale_price",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
