# Generated by Django 5.1.4 on 2024-12-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0025_sale_sale_price"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Signup",
        ),
        migrations.AlterField(
            model_name="item",
            name="bulk_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="chef_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="gst",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="quantity",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="retailer_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="tsales",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sale",
            name="discount",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sale",
            name="gst_subtotal",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sale",
            name="payment_status",
            field=models.CharField(
                choices=[("paid", "paid"), ("unpaid", "unpaid"), ("return", "return")],
                default="unpaid",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="sale",
            name="price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sale",
            name="quantity",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sale",
            name="sale_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sale",
            name="subtotal",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
