# Generated by Django 5.1.4 on 2024-12-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0026_delete_signup_alter_item_bulk_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="return_status",
            field=models.CharField(
                choices=[("yes", "yes"), ("no", "no")], default="no", max_length=10
            ),
        ),
    ]
