# Generated by Django 5.1.4 on 2024-12-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0027_sale_return_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="return_status",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
