# Generated by Django 5.1.4 on 2024-12-29 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0028_alter_sale_return_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cater",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cater_id", models.CharField(blank=True, max_length=20, null=True)),
                ("i_type", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "type_status",
                    models.CharField(
                        choices=[("in", "in"), ("out", "out")],
                        default="in",
                        max_length=5,
                    ),
                ),
                ("quantity", models.FloatField(blank=True, null=True)),
                ("price", models.FloatField(blank=True, null=True)),
                (
                    "customer_name",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                (
                    "customer_addrs",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "customer_mobile",
                    models.IntegerField(blank=True, max_length=10, null=True),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[("paid", "paid"), ("unpaid", "unpaid")],
                        default="unpaid",
                        max_length=10,
                    ),
                ),
                ("sale_price", models.FloatField(blank=True, null=True)),
                ("gst", models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
