# Generated by Django 5.1.4 on 2024-12-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0029_cater"),
    ]

    operations = [
        migrations.AddField(
            model_name="cater",
            name="gst_subtotal",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
