# Generated by Django 5.1.4 on 2024-12-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0030_cater_gst_subtotal"),
    ]

    operations = [
        migrations.AddField(
            model_name="cater",
            name="subtotal",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
