# Generated by Django 5.1.4 on 2024-12-29 17:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0031_cater_subtotal"),
    ]

    operations = [
        migrations.AddField(
            model_name="cater",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
